"""create companies

Revision ID: 46918f7dc9da
Revises: 383dbe0983df
Create Date: 2020-07-01 14:43:38.550415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46918f7dc9da'
down_revision = '383dbe0983df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'items', 'companies', ['companyId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_table('companies')
    # ### end Alembic commands ###
