name: dillinger
version: master
summary: The last Markdown editor, ever
description: |
  Dillinger is a cloud-enabled, mobile-ready, offline-storage, AngularJS powered
  HTML5 Markdown editor.

confinement: strict

apps:
  server:
    command: node $SNAP/lib/node_modules/Dillinger/app.js
    plugs: [network-bind]
    daemon: simple

parts:
  dillinger:
    source: .
    plugin: nodejs
    build-packages: [bzip2, git]
    node-packages: [is-property]
