[book]
authors = ["Phil Freeman"]
language = "en"
multilingual = false
src = "text"
title = "PureScript by Example"
[output.html]
git-repository-url = "https://github.com/purescript-contrib/purescript-book"
