if: tag IS blank
git:
  depth: 1
sudo: required
language: node_js

node_js:
  - "8"
  - "9"

env:
  - CXX=g++-4.8

addons:
    chrome: stable

before_install:
  - npm install -g lerna@3.0.0-beta.0 yarn
  - ./scripts/checkout-opticss.sh ../opticss

install:
  - lerna bootstrap --registry=https://registry.npmjs.org/

script: lerna run test
