'use strict';
const bcrypt = require('bcryptjs');
const { query } = require('express');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const users = await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'memu',
          email: 'memu@email.com',
          password: bcrypt.hashSync('password'),
          dob: new Date('03-21-1995'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    );

    const quests = await queryInterface.bulkInsert(
      'Quests',
      [
        {
          title: 'Warring Matriarchs',
          description: 'The islands of Vidalia are at war. The Matriarchs seem unwilling to let go of their grudges.',
          creatorId: users[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      { returning: true }
    );

    const weapons = await queryInterface.bulkInsert(
      'Weapons',
      [
        {
          name: 'Axe',
          description: 'A standard axe, the handle wrapped in leather fits nicely in your hand.',
          hitDice: '2d4',
          damageType: 'none',
          cost: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bow',
          description: 'A standard bow, cheaply made but with care.',
          hitDice: '1d12',
          damageType: 'none',
          cost: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Blue Flame Sword',
          description: 'Well, if you got nothing else.',
          hitDice: '2d10',
          damageType: 'fire',
          cost: 101,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Crossbow',
          description: 'A mechanical, one handed bow. Iron sights are built onto the top.',
          hitDice: '2d8',
          damageType: 'none',
          cost: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dagger',
          description: 'The weapon of choice for assassins.',
          hitDice: '2d4',
          damageType: 'none',
          cost: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dark Dagger',
          description: 'This dagger is imbued with dark magic. Strange symbols are carved into the handle.',
          hitDice: '2d8',
          damageType: 'dark',
          cost: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Elephant Tusk',
          description: 'Beast hunters are proud of their trophies, and an elephant tusk doubles as a crude dagger.',
          hitDice: '3d6',
          damageType: 'Lightning',
          cost: 27,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Frail Wand',
          description: 'Well, if you got nothing else.',
          hitDice: '2d4',
          damageType: 'none',
          cost: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gauntlet',
          description: 'Fists of steel are a force to be reckoned with.',
          hitDice: '4d6',
          damageType: 'none',
          cost: 68,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gloves',
          description: 'Leather gloves to protect your hands. Useful for the hand to hand combat types.',
          hitDice: '4d4',
          damageType: 'none',
          cost: 40,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Greatsword of the Moonlight Goddess.',
          description: 'This weapon reminds you of something, or maybe it was something said to you in passing. It glows with the milky light of the moon.',
          hitDice: '4d12',
          damageType: 'Dark',
          cost: 223,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Greatsword',
          description: 'A really big sword. The previous owner was a strawberry, or their name was strawberry? Hard to say.',
          hitDice: '2d8',
          damageType: 'none',
          cost: 65,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Greataxe',
          description: 'This axe is big, go hit something with it.',
          hitDice: '3d6',
          damageType: 'none',
          cost: 65,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Holy Sword',
          description: 'This sword was once weilded by a celestial being. It glows when evil is near.',
          hitDice: '1d8',
          damageType: 'holy',
          cost: 50,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Holy Axe',
          description: 'This axe was once weilded by a celestial being. It glows when evil is near.',
          hitDice: '2d4',
          damageType: 'holy',
          cost: 50,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Hell's Bane",
          description: 'An axe blessed by a primordial being for the purpose of purging evil.',
          hitDice: '4d10',
          damageType: 'holy',
          cost: 200,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ilos Bow',
          description: 'Master craftswoman Ilos creates the best bows. This bow especially was her crowning achievement.',
          hitDice: '3d20',
          damageType: 'none',
          cost: 500,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Javelin',
          description: 'Basically a spear.',
          hitDice: '1d12',
          damageType: 'none',
          cost: 36,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'King Slayer',
          description: 'Not to be confused with a strange man. Forged during a revolution, and weilded by a rebel.',
          hitDice: '5d8',
          damageType: 'Holy',
          cost: 89,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Knife',
          description: 'Make do.',
          hitDice: '2d4',
          damageType: 'none',
          cost: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Long Bow',
          description: 'A larger bow than standard.',
          hitDice: '1d20',
          damageType: 'none',
          cost: 33,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Mighty Greataxe',
          description: 'This axe seems to big to hold, but all the better to crush people with.',
          hitDice: '2d12',
          damageType: 'none',
          cost: 72,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Nevermore',
          description: 'A master assassin blade.',
          hitDice: '9d8',
          damageType: 'poison',
          cost: 234,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lake Maker',
          description: 'A water elemental, on the brink of death pushed his will into this axe.',
          hitDice: '12d10',
          damageType: 'none',
          cost: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Poison Axe',
          description: 'A master assassin blade.',
          hitDice: '3d6',
          damageType: 'poison',
          cost: 234,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Poison Sword',
          description: 'A master assassin blade.',
          hitDice: '9d8',
          damageType: 'poison',
          cost: 234,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Queen's Revenge",
          description: 'The blade of the first Queen, from a time when Vidalia was ruled under one monarch.',
          hitDice: '13d8',
          damageType: 'none',
          cost: 234,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Red Scythe",
          description: "The pole of this weapon is adorned with rubies.",
          hitDice: '6d12',
          damageType: 'fire',
          cost: 234,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    )

    const items = await queryInterface.bulkInsert(
      'Items',
      [
        // {
        //   name: 'Antidote',
        //   description: 'Renders poison useless.',
        //   cost: 5,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        {
          name: 'Arrow',
          description: 'A standard, sturdy, all purpose arrow.',
          cost: 3,
          createdAt: new Date(),
          updatedAt: new Date(),

        },
        // {
        //   name: 'Bottled Wish',
        //   description: 'Resurrect a teamate on the brink of death.',
        //   cost: 60,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        {
          name: 'Black Powder Bomb',
          description: 'Deals 100 damage...if it hits them.',
          cost: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Chips',
          description: 'Why are these so overpriced? Heals 5 health if consumed.',
          cost: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Orange Cake',
          description: 'Restore an ability for two additional uses.',
          cost: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fire Arrow',
          description: 'Deals fire damage.',
          cost: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Healing Potion (S)',
          description: 'Heals 10 health.',
          cost: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Healing Potion (M)',
          description: 'Heals 20 health.',
          cost: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Healing Potion (L)',
          description: 'Heals 60 health.',
          cost: 50,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Poison Arrow',
          description: 'Deals poison damage.',
          cost: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Shock Arrow',
          description: 'Deals lightning damage.',
          cost: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    )

    const abilities = await queryInterface.bulkInsert(
      'Abilities',
      [
        {
          name: 'Blazing Vortex',
          description: 'Deals flame damage, chance to burn.',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Blessing',
          description: 'User has chance to deal double damage.',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Crushing Blow',
          description: 'User has chance to crush limbs. If successful, recipient deals half damage for duration of the fight.',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Despair',
          description: 'Enemy becomes overwhelmed with despair. Cannot use a standard attack, (but can still use abilities), for two turns.',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fire Breath',
          description: 'The user hurls a ball of fire from their mouth. Entire group takes fire damge.',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Lullaby',
          description: 'Sings enemy to sleep, lasts two turns.',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Poison Bite',
          description: 'The user deals poison damage, chance to poison.',
          uses: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Prayer',
          description: 'The user prays to their deity. Chance to heal',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        // {
        //   name: 'Soothing Water',
        //   description: 'Heals Burn effect.',
        //   uses: 6,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        // {
        //   name: 'Shock',
        //   description: 'Chance to stun. They cannot use abilities this turn.',
        //   uses: 3,
        //   createdAt: new Date(),
        //   updatedAt: new Date(),
        // },
        {
          name: 'Nightmares',
          description: 'The user traps the recipient of this ability in a nightmare. Causing hellucinations. Halves their chances to land attacks for one turn.',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Teleport',
          description: 'The user creates a wormhole, passing through and appearing somewhere else. Cancels out any damge dealt by the next attack.',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      { returning: true }
    )

    const spells = await queryInterface.bulkInsert(
      'Spells',
      [
        {
          name: 'Comet Calling',
          description: 'Call upon the heavens to rain hell on the enemy. Damages entire enemy team.',
          damageType: 'earth',
          hitDice: '1d20',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Earth Scatter',
          description: 'Shards of earth rise and fly in the direction of a single target.',
          damageType: 'earth',
          hitDice: '12d4',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Celestial Light',
          description: 'The heavens smite one target.',
          damageType: 'holy',
          hitDice: '2d20',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fire Whip',
          description: 'A fiery whip burns your target.',
          damageType: 'fire',
          hitDice: '3d8',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Hail Storm',
          description: 'Clouds gather over the enemy team, raining hail shards from the sky.',
          damageType: 'water',
          hitDice: '12d4',
          uses: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Water Prison',
          description: 'A orb of water encases one enemy, suffocating them.',
          damageType: 'water',
          hitDice: '2d20',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Soul Spear',
          description: 'The user casts a massive spear of energy containing the will of the soul.',
          damageType: 'none',
          hitDice: '1d20',
          uses: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Soul Barrage',
          description: 'The soul cries out in fear, casting a barrage of attacks at a single target.',
          damageType: 'none',
          hitDice: '6d4',
          uses: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Shockwave',
          description: 'Lightning slither across the ground and through the air at an incredible speed. Shocking one target.',
          damageType: 'lightning',
          hitDice: '6d10',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Toxic Orbs',
          description: 'Casts 12 orbs of poisonous smoke.',
          damageType: 'poison',
          hitDice: '12d4',
          uses: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Torment',
          description: 'Darkness shrouds the mind of the target.',
          damageType: 'dark',
          hitDice: '3d8',
          uses: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    )

    const starters = await queryInterface.bulkInsert(
      'Starters',
      [
        {
          name: 'Barbaric Starter',
          description: 'The starter equipment for barbarians.',
          weaponId: weapons[12].id,
          itemId: items[1].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cleric Starter',
          description: 'The starter equipment for clerics.',
          weaponId: weapons[13].id,
          spellId: spells[2].id,
          itemId: items[3].id,
          createdAt: new Date(),
          updatedAt: new Date(),

        },
        {
          name: 'Fighter Starter',
          description: 'The starter equipment for fighters.',
          weaponId: weapons[9].id,
          itemId: items[1].id,
          createdAt: new Date(),
          updatedAt: new Date(),

        },
        {
          name: 'Ranger Starter',
          description: 'The starter equipment for rangers.',
          weaponId: weapons[1].id,
          itemId: items[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),

        },
        {
          name: 'Assassin Starter',
          description: 'The starter equipment for rangers.',
          weaponId: weapons[4].id,
          itemId: items[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),

        },
        {
          name: 'Sorcerer Starter',
          description: 'The starter equipment for sorcerers.',
          weaponId: weapons[7].id,
          itemId: items[3].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    )

    const classes = await queryInterface.bulkInsert(
      'Classes',
      [
        {
          name: 'Barbarian',
          description: 'Barbarians are strong individuals, although they might not be the brightest of the bunch they make up for it with brute force.',
          acMod: 3,
          hpMod: 3,
          strMod: 3,
          dexMod: 0,
          constMod: 2,
          intelMod: -1,
          wisdMod: -1,
          charMod: 0,
          starterId: starters[0].id,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cleric',
          description: 'A fighter for the devine.',
          acMod: 2,
          hpMod: 4,
          strMod: 2,
          dexMod: 1,
          constMod: 3,
          intelMod: 0,
          wisdMod: 0,
          charMod: 1,
          starterId: starters[1].id,
          weakness: 'dark',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fighter',
          description: 'A master of hand to hand combat.',
          acMod: 0,
          hpMod: 1,
          strMod: 3,
          dexMod: 3,
          constMod: 1,
          intelMod: 0,
          wisdMod: 0,
          charMod: 3,
          starterId: starters[2].id,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ranger',
          description: 'A ranger rarely misses their target. Incredibly skilled with the bow.',
          acMod: 0,
          hpMod: 2,
          strMod: 1,
          dexMod: 5,
          constMod: 2,
          intelMod: 1,
          wisdMod: 2,
          charMod: 5,
          starterId: starters[3].id,
          weakness: 'poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Assassin',
          description: 'Assassins are highly adaptive and deal lots of damage very quickly.',
          acMod: 0,
          hpMod: 1,
          strMod: 1,
          dexMod: 5,
          constMod: 2,
          intelMod: 3,
          wisdMod: 3,
          charMod: 2,
          starterId: starters[4].id,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sorcerer',
          description: 'Sorcerers study arcan magic, long forgotten by the rest of the world.',
          acMod: -1,
          hpMod: 0,
          strMod: 0,
          dexMod: 0,
          constMod: 4,
          intelMod: 5,
          wisdMod: 5,
          charMod: 3,
          starterId: starters[5].id,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true}
    )

    const characters = await queryInterface.bulkInsert(
      'Characters',
      [
        {
          name: 'Onion Queen Memu',
          story: 'Once a ruler of vidalia, she vanished 200 years ago during the Sky Leek.',
          armorClass: 10,
          hitPoints: 12,
          strength: 11,
          dexterity: 15,
          constitution: 12,
          intelligence: 11,
          wisdom: 12,
          charisma: 15,
          abilityId: abilities[9].id,
          classId: classes[3].id,
          creatorId: users[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Sir Shallot Allium',
          story: 'Trusted right hand man of Memu.',
          armorClass: 13,
          hitPoints: 13,
          strength: 13,
          dexterity: 10,
          constitution: 12,
          intelligence: 9,
          wisdom: 9,
          charisma: 10,
          abilityId: abilities[2].id,
          classId: classes[0].id,
          creatorId: users[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    )

    const enemies = await queryInterface.bulkInsert(
      'Enemies',
      [
        {
          name: 'Aboleth',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 135,
          hitDice: '18d10',
          strength: 21,
          dexterity: 9,
          constitution: 15,
          intelligence: 18,
          wisdom: 15,
          charisma: 18,
          challenge: 10,
          xpReward: 5900,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Acolyte',
          size: 'Medium',
          type: 'Humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 10,
          hitPoints: 9,
          hitDice: '2d8',
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 14,
          charisma: 11,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Black Dragon',
          size: 'Huge',
          type: 'Dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 195,
          hitDice: '17d12',
          strength: 23,
          dexterity: 14,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Blue Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 225,
          hitDice: '18d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 16,
          xpReward: 15000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Brass Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 13,
          xpReward: 10000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Bronze Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 212,
          hitDice: '17d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 15,
          xpReward: 13000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Copper Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Gold Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 24,
          challenge: 17,
          xpReward: 18000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Green Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 207,
          hitDice: '18d12',
          strength: 23,
          dexterity: 12,
          constitution: 21,
          intelligence: 18,
          wisdom: 15,
          charisma: 17,
          challenge: 15,
          xpReward: 13000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Red Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 17,
          xpReward: 18000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult Silver Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 243,
          hitDice: '18d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 16,
          xpReward: 15000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Adult White Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '16d12',
          strength: 22,
          dexterity: 10,
          constitution: 22,
          intelligence: 8,
          wisdom: 12,
          charisma: 12,
          challenge: 13,
          xpReward: 10000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Air Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Nuetral',
          armorClass: 15,
          hitPoints: 90,
          hitDice: '12d10',
          strength: 14,
          dexterity: 20,
          constitution: 14,
          intelligence: 6,
          wisdom: 10,
          charisma: 6,
          challenge: 5,
          xpReward: 1800,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Black Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Blue Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Laeful Evil',
          armorClass: 22,
          hitPoints: 481,
          hitDice: '26d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 23,
          xpReward: 50000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Brass Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 20,
          hitPoints: 297,
          hitDice: '17d20',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 20,
          xpReward: 25000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Bronze Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 444,
          hitDice: '24d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 22,
          xpReward: 41000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Copper Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 21,
          hitPoints: 350,
          hitDice: '20d20',
          strength: 27,
          dexterity: 12,
          constitution: 25,
          intelligence: 20,
          wisdom: 17,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Gold Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 546,
          hitDice: '28d20',
          strength: 30,
          dexterity: 14,
          constitution: 29,
          intelligence: 18,
          wisdom: 17,
          charisma: 28,
          challenge: 24,
          xpReward: 62000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Green Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 21,
          hitPoints: 385,
          hitDice: '22d20',
          strength: 27,
          dexterity: 12,
          constitution: 25,
          intelligence: 20,
          wisdom: 17,
          charisma: 19,
          challenge: 22,
          xpReward: 41000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Red Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 30,
          dexterity: 10,
          constitution: 29,
          intelligence: 18,
          wisdom: 15,
          charisma: 23,
          challenge: 24,
          xpReward: 62000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient Silver Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 487,
          hitDice: '25d20',
          strength: 30,
          dexterity: 10,
          constitution: 29,
          intelligence: 18,
          wisdom: 15,
          charisma: 23,
          challenge: 23,
          xpReward: 50000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ancient White Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 20,
          hitPoints: 333,
          hitDice: '18d20',
          strength: 26,
          dexterity: 10,
          constitution: 26,
          intelligence: 10,
          wisdom: 13,
          charisma: 14,
          challenge: 20,
          xpReward: 25000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Androsphinx',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Lawful Nuetral',
          armorClass: 17,
          hitPoints: 199,
          hitDice: '19d10',
          strength: 22,
          dexterity: 10,
          constitution: 20,
          intelligence: 16,
          wisdom: 18,
          charisma: 23,
          challenge: 17,
          xpReward: 18000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Animated Armor',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 18,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 14,
          dexterity: 11,
          constitution: 13,
          intelligence: 1,
          wisdom: 3,
          charisma: 1,
          challenge: 1,
          xpReward: 200,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ankheg',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 39,
          hitDice: '6d10',
          strength: 17,
          dexterity: 11,
          constitution: 13,
          intelligence: 1,
          wisdom: 13,
          charisma: 6,
          challenge: 2,
          xpReward: 250,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ape',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 18,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 16,
          dexterity: 14,
          constitution: 14,
          intelligence: 6,
          wisdom: 12,
          charisma: 7,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Archmage',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 12,
          hitPoints: 99,
          hitDice: '18d8',
          strength: 10,
          dexterity: 14,
          constitution: 12,
          intelligence: 20,
          wisdom: 15,
          charisma: 16,
          challenge: 12,
          xpReward: 8400,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Assassin',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 15,
          hitPoints: 78,
          hitDice: '12d8',
          strength: 11,
          dexterity: 16,
          constitution: 14,
          intelligence: 13,
          wisdom: 11,
          charisma: 10,
          challenge: 8,
          xpReward: 3900,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Awakened Shrub',
          size: 'Small',
          type: 'plant',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 9,
          hitPoints: 10,
          hitDice: '3d6',
          strength: 3,
          dexterity: 8,
          constitution: 11,
          intelligence: 10,
          wisdom: 10,
          charisma: 6,
          challenge: 0,
          xpReward: 10,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Awakened Tree',
          size: 'Huge',
          type: 'plant',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 49,
          hitDice: '7d12',
          strength: 19,
          dexterity: 6,
          constitution: 15,
          intelligence: 10,
          wisdom: 10,
          charisma: 7,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Axe Beak',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 19,
          hitDice: '3d10',
          strength: 3,
          dexterity: 8,
          constitution: 11,
          intelligence: 10,
          wisdom: 10,
          charisma: 6,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Azer',
          size: 'Medium',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Lawful Neutral',
          armorClass: 17,
          hitPoints: 39,
          hitDice: '6d8',
          strength: 17,
          dexterity: 12,
          constitution: 15,
          intelligence: 12,
          wisdom: 13,
          charisma: 10,
          challenge: 2,
          xpReward: 450,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Baboon',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 3,
          hitDice: '1d6',
          strength: 8,
          dexterity: 14,
          constitution: 11,
          intelligence: 4,
          wisdom: 12,
          charisma: 6,
          challenge: 0,
          xpReward: 10,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Badger',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 3,
          hitDice: '1d4',
          strength: 4,
          dexterity: 11,
          constitution: 12,
          intelligence: 2,
          wisdom: 12,
          charisma: 4,
          challenge: 0,
          xpReward: 10,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Balor',
          size: 'Huge',
          type: 'fiend',
          subtype: 'demon',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 262,
          hitDice: '21d12',
          strength: 26,
          dexterity: 15,
          constitution: 22,
          intelligence: 20,
          wisdom: 16,
          charisma: 22,
          challenge: 19,
          xpReward: 22000,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bandit',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 12,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 11,
          dexterity: 12,
          constitution: 12,
          intelligence: 10,
          wisdom: 10,
          charisma: 10,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bandit Captain',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 15,
          hitPoints: 65,
          hitDice: '10d8',
          strength: 11,
          dexterity: 16,
          constitution: 14,
          intelligence: 14,
          wisdom: 11,
          charisma: 14,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Barbed Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 15,
          hitPoints: 110,
          hitDice: '13d8',
          strength: 16,
          dexterity: 17,
          constitution: 18,
          intelligence: 12,
          wisdom: 14,
          charisma: 14,
          challenge: 5,
          xpReward: 1800,
          weakness: 'water/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Basilisk',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 16,
          dexterity: 8,
          constitution: 15,
          intelligence: 2,
          wisdom: 8,
          charisma: 7,
          challenge: 3,
          xpReward: 700,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bat',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 1,
          hitDice: '1d4',
          strength: 2,
          dexterity: 15,
          constitution: 8,
          intelligence: 2,
          wisdom: 12,
          charisma: 4,
          challenge: 0,
          xpReward: 10,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bearded Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 13,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 16,
          dexterity: 15,
          constitution: 15,
          intelligence: 9,
          wisdom: 11,
          charisma: 11,
          challenge: 3,
          xpReward: 700,
          weakness: 'water/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Behir',
          size: 'Huge',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 17,
          hitPoints: 168,
          hitDice: '16d12',
          strength: 23,
          dexterity: 16,
          constitution: 18,
          intelligence: 7,
          wisdom: 14,
          charisma: 12,
          challenge: 11,
          xpReward: 7200,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Berserker',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any chaotic alignment',
          armorClass: 13,
          hitPoints: 67,
          hitDice: '9d8',
          strength: 16,
          dexterity: 12,
          constitution: 17,
          intelligence: 19,
          wisdom: 11,
          charisma: 9,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Black Bear',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 19,
          hitDice: '3d8',
          strength: 15,
          dexterity: 10,
          constitution: 14,
          intelligence: 2,
          wisdom: 12,
          charisma: 7,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Black Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 17,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 15,
          dexterity: 14,
          constitution: 13,
          intelligence: 10,
          wisdom: 11,
          charisma: 13,
          challenge: 2,
          xpReward: 450,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Black Pudding',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 7,
          hitPoints: 85,
          hitDice: '10d10',
          strength: 16,
          dexterity: 5,
          constitution: 16,
          intelligence: 1,
          wisdom: 6,
          charisma: 1,
          challenge: 4,
          xpReward: 1100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Blink Dog',
          size: 'Medium',
          type: 'fey',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 13,
          hitPoints: 22,
          hitDice: '4d8',
          strength: 12,
          dexterity: 17,
          constitution: 12,
          intelligence: 10,
          wisdom: 13,
          charisma: 11,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Blood Hawk',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 7,
          hitDice: '2d6',
          strength: 6,
          dexterity: 14,
          constitution: 10,
          intelligence: 3,
          wisdom: 14,
          charisma: 5,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Blue Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 17,
          dexterity: 10,
          constitution: 15,
          intelligence: 12,
          wisdom: 11,
          charisma: 15,
          challenge: 3,
          xpReward: 700,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Boar',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 17,
          hitPoints: 1,
          hitDice: '2d8',
          strength: 13,
          dexterity: 11,
          constitution: 12,
          intelligence: 2,
          wisdom: 9,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bone Devil',
          size: 'Large',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 142,
          hitDice: '15d10',
          strength: 18,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 16,
          challenge: 12,
          xpReward: 8400,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Brass Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 16,
          hitPoints: 16,
          hitDice: '3d8',
          strength: 15,
          dexterity: 10,
          constitution: 13,
          intelligence: 10,
          wisdom: 11,
          charisma: 13,
          challenge: 1,
          xpReward: 100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bronze Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 17,
          hitPoints: 32,
          hitDice: '5d8',
          strength: 17,
          dexterity: 10,
          constitution: 15,
          intelligence: 12,
          wisdom: 11,
          charisma: 15,
          challenge: 2,
          xpReward: 450,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Brown Bear',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 34,
          hitDice: '4d10',
          strength: 19,
          dexterity: 10,
          constitution: 16,
          intelligence: 2,
          wisdom: 13,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Bulette',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 17,
          hitPoints: 94,
          hitDice: '9d10',
          strength: 19,
          dexterity: 11,
          constitution: 21,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 1,
          xpReward: 200,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Camel',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 9,
          hitPoints: 15,
          hitDice: '2d10',
          strength: 16,
          dexterity: 8,
          constitution: 14,
          intelligence: 2,
          wisdom: 8,
          charisma: 5,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'poison/fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cat',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 2,
          hitDice: '1d4',
          strength: 3,
          dexterity: 15,
          constitution: 10,
          intelligence: 3,
          wisdom: 12,
          charisma: 7,
          challenge: 0,
          xpReward: 10,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Centaur',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Good',
          armorClass: 12,
          hitPoints: 45,
          hitDice: '6d10',
          strength: 18,
          dexterity: 14,
          constitution: 14,
          intelligence: 9,
          wisdom: 13,
          charisma: 11,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Chain Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 16,
          hitPoints: 85,
          hitDice: '10d8',
          strength: 18,
          dexterity: 15,
          constitution: 18,
          intelligence: 11,
          wisdom: 12,
          charisma: 14,
          challenge: 8,
          xpReward: 3900,
          weakness: 'water/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Chimera',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 14,
          hitPoints: 114,
          hitDice: '12d10',
          strength: 19,
          dexterity: 11,
          constitution: 19,
          intelligence: 3,
          wisdom: 14,
          charisma: 10,
          challenge: 6,
          xpReward: 2300,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Chuul',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 16,
          hitPoints: 93,
          hitDice: '11d10',
          strength: 19,
          dexterity: 10,
          constitution: 16,
          intelligence: 35,
          wisdom: 11,
          charisma: 5,
          challenge: 4,
          xpReward: 1100,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Clay Golem',
          size: 'Large',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 133,
          hitDice: '14d10',
          strength: 20,
          dexterity: 9,
          constitution: 18,
          intelligence: 3,
          wisdom: 8,
          charisma: 1,
          challenge: 9,
          xpReward: 5000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cloaker',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Chaotic Neutral',
          armorClass: 14,
          hitPoints: 78,
          hitDice: '12d10',
          strength: 17,
          dexterity: 15,
          constitution: 12,
          intelligence: 13,
          wisdom: 12,
          charisma: 14,
          challenge: 8,
          xpReward: 3900,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cloud Giant',
          size: 'Huge',
          type: 'giant',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 14,
          hitPoints: 200,
          hitDice: '16d12',
          strength: 27,
          dexterity: 10,
          constitution: 2,
          intelligence: 12,
          wisdom: 16,
          charisma: 16,
          challenge: 9,
          xpReward: 5000,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cockatrice',
          size: 'Small',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 27,
          hitDice: '6d6',
          strength: 6,
          dexterity: 12,
          constitution: 12,
          intelligence: 2,
          wisdom: 13,
          charisma: 5,
          challenge: 6,
          xpReward: 2300,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Commoner',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 10,
          hitPoints: 4,
          hitDice: '1d8',
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 10,
          charisma: 10,
          challenge: 0,
          xpReward: 10,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Constrictor Snake',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 13,
          hitDice: '2d10',
          strength: 15,
          dexterity: 14,
          constitution: 12,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Copper Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 16,
          hitPoints: 22,
          hitDice: '4d8',
          strength: 15,
          dexterity: 12,
          constitution: 13,
          intelligence: 14,
          wisdom: 11,
          charisma: 13,
          challenge: 1,
          xpReward: 200,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Couatl',
          size: 'Medium',
          type: 'celestial',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 97,
          hitDice: '13d8',
          strength: 16,
          dexterity: 20,
          constitution: 17,
          intelligence: 18,
          wisdom: 20,
          charisma: 18,
          challenge: 4,
          xpReward: 1100,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Crab',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 2,
          hitDice: '1d4',
          strength: 2,
          dexterity: 11,
          constitution: 10,
          intelligence: 1,
          wisdom: 8,
          charisma: 2,
          challenge: 0,
          xpReward: 10,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Crocodile',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 19,
          hitDice: '2d10',
          strength: 15,
          dexterity: 10,
          constitution: 13,
          intelligence: 1,
          wisdom: 10,
          charisma: 5,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cult Fanatic',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any evil alignment',
          armorClass: 12,
          hitPoints: 13,
          hitDice: '2d10',
          strength: 15,
          dexterity: 14,
          constitution: 12,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Cultist',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any evil alignment',
          armorClass: 12,
          hitPoints: 9,
          hitDice: '2d8',
          strength: 11,
          dexterity: 12,
          constitution: 10,
          intelligence: 10,
          wisdom: 11,
          charisma: 10,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dark Mantle',
          size: 'Small',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 22,
          hitDice: '5d6',
          strength: 16,
          dexterity: 12,
          constitution: 13,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Death Dog',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 12,
          hitPoints: 39,
          hitDice: '6d8',
          strength: 15,
          dexterity: 14,
          constitution: 14,
          intelligence: 3,
          wisdom: 13,
          charisma: 6,
          challenge: 1,
          xpReward: 200,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Deep Gnome Svirfneblin',
          size: 'Small',
          type: 'humanoid',
          subtype: 'gnome',
          alignment: 'Neutral Good',
          armorClass: 15,
          hitPoints: 16,
          hitDice: '3d6',
          strength: 16,
          dexterity: 14,
          constitution: 14,
          intelligence: 12,
          wisdom: 10,
          charisma: 9,
          challenge: 0.5,
          xpReward: 50,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Deer',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d8',
          strength: 11,
          dexterity: 16,
          constitution: 11,
          intelligence: 2,
          wisdom: 14,
          charisma: 5,
          challenge: 0,
          xpReward: 10,
          weakness: 'fire/poison/earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Deva',
          size: 'Small',
          type: 'celestial',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 17,
          hitPoints: 136,
          hitDice: '16d8',
          strength: 18,
          dexterity: 18,
          constitution: 18,
          intelligence: 17,
          wisdom: 20,
          charisma: 20,
          challenge: 10,
          xpReward: 5900,
          weakness: 'dark',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dire Wolf',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 37,
          hitDice: '5d10',
          strength: 17,
          dexterity: 15,
          constitution: 15,
          intelligence: 3,
          wisdom: 12,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Djinni',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 17,
          hitPoints: 161,
          hitDice: '14d10',
          strength: 21,
          dexterity: 15,
          constitution: 22,
          intelligence: 15,
          wisdom: 16,
          charisma: 20,
          challenge: 11,
          xpReward: 7200,
          weakness: 'dark',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Doppleganger',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 14,
          hitPoints: 54,
          hitDice: '5d6',
          strength: 16,
          dexterity: 12,
          constitution: 15,
          intelligence: 12,
          wisdom: 12,
          charisma: 8,
          challenge: 5,
          xpReward: 1800,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Draft Horse',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 19,
          hitDice: '3d10',
          strength: 16,
          dexterity: 12,
          constitution: 13,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dragon Turtle',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 20,
          hitPoints: 341,
          hitDice: '22d20',
          strength: 25,
          dexterity: 10,
          constitution: 20,
          intelligence: 10,
          wisdom: 12,
          charisma: 12,
          challenge: 17,
          xpReward: 18000,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dretch',
          size: 'Small',
          type: 'fiend',
          subtype: 'demon',
          alignment: 'Chaotic Evil',
          armorClass: 11,
          hitPoints: 18,
          hitDice: '4d6',
          strength: 11,
          dexterity: 11,
          constitution: 12,
          intelligence: 5,
          wisdom: 8,
          charisma: 3,
          challenge: 0.25,
          xpReward: 25,
          weakness: 'fire/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Drider',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 123,
          hitDice: '13d10',
          strength: 16,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 12,
          challenge: 6,
          xpReward: 2300,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Drow',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'elf',
          alignment: 'Neutral Evil',
          armorClass: 15,
          hitPoints: 13,
          hitDice: '3d8',
          strength: 10,
          dexterity: 14,
          constitution: 10,
          intelligence: 11,
          wisdom: 11,
          charisma: 12,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Druid',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'Chaotic Evil',
          armorClass: 11,
          hitPoints: 27,
          hitDice: '5d8',
          strength: 10,
          dexterity: 12,
          constitution: 13,
          intelligence: 12,
          wisdom: 15,
          charisma: 11,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dryad',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 123,
          hitDice: '13d10',
          strength: 16,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 12,
          challenge: 6,
          xpReward: 2300,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Dryad',
          size: 'Medium',
          type: 'fey',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 11,
          hitPoints: 22,
          hitDice: '5d8',
          strength: 10,
          dexterity: 12,
          constitution: 11,
          intelligence: 14,
          wisdom: 15,
          charisma: 18,
          challenge: 1,
          xpReward: 200,
          weakness: 'dark/lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Eagle',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 3,
          hitDice: '1d6',
          strength: 6,
          dexterity: 15,
          constitution: 10,
          intelligence: 2,
          wisdom: 14,
          charisma: 7,
          challenge: 0,
          xpReward: 10,
          weakness: 'lighting',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Earth Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 17,
          hitPoints: 126,
          hitDice: '12d10',
          strength: 20,
          dexterity: 8,
          constitution: 20,
          intelligence: 5,
          wisdom: 10,
          charisma: 5,
          challenge: 5,
          xpReward: 1800,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Efreeti',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 200,
          hitDice: '16d10',
          strength: 22,
          dexterity: 12,
          constitution: 24,
          intelligence: 16,
          wisdom: 15,
          charisma: 16,
          challenge: 11,
          xpReward: 7200,
          weakness: 'water/holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Elephant',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 76,
          hitDice: '8d12',
          strength: 22,
          dexterity: 9,
          constitution: 17,
          intelligence: 3,
          wisdom: 11,
          charisma: 12,
          challenge: 4,
          xpReward: 1100,
          weakness: 'fire/water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Elk',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 13,
          hitDice: '2d10',
          strength: 16,
          dexterity: 10,
          constitution: 12,
          intelligence: 2,
          wisdom: 10,
          charisma: 6,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Erinyes',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 18,
          hitPoints: 153,
          hitDice: '18d8',
          strength: 18,
          dexterity: 16,
          constitution: 18,
          intelligence: 14,
          wisdom: 14,
          charisma: 18,
          challenge: 12,
          xpReward: 8400,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ettercap',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 13,
          hitPoints: 44,
          hitDice: '8d8',
          strength: 14,
          dexterity: 15,
          constitution: 13,
          intelligence: 7,
          wisdom: 12,
          charisma: 8,
          challenge: 2,
          xpReward: 450,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ettin',
          size: 'Large',
          type: 'giant',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 12,
          hitPoints: 85,
          hitDice: '10d10',
          strength: 21,
          dexterity: 8,
          constitution: 17,
          intelligence: 6,
          wisdom: 10,
          charisma: 8,
          challenge: 4,
          xpReward: 1100,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fire Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 13,
          hitPoints: 102,
          hitDice: '12d10',
          strength: 10,
          dexterity: 17,
          constitution: 16,
          intelligence: 6,
          wisdom: 10,
          charisma: 7,
          challenge: 5,
          xpReward: 1800,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Fire Giant',
          size: 'Huge',
          type: 'giant',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 18,
          hitPoints: 162,
          hitDice: '13d12',
          strength: 25,
          dexterity: 9,
          constitution: 23,
          intelligence: 10,
          wisdom: 14,
          charisma: 13,
          challenge: 9,
          xpReward: 5000,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Flesh Golem',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 9,
          hitPoints: 93,
          hitDice: '11d8',
          strength: 19,
          dexterity: 9,
          constitution: 18,
          intelligence: 6,
          wisdom: 10,
          charisma: 5,
          challenge: 5,
          xpReward: 1800,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Flying Snake',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 5,
          hitDice: '2d4',
          strength: 4,
          dexterity: 18,
          constitution: 11,
          intelligence: 2,
          wisdom: 12,
          charisma: 5,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'fire/lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Flying Sword',
          size: 'Small',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 17,
          hitPoints: 17,
          hitDice: '5d6',
          strength: 12,
          dexterity: 15,
          constitution: 11,
          intelligence: 1,
          wisdom: 5,
          charisma: 1,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Frog',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 1,
          hitDice: '1d4',
          strength: 1,
          dexterity: 13,
          constitution: 8,
          intelligence: 1,
          wisdom: 8,
          charisma: 3,
          challenge: 0,
          xpReward: 0,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Frost Giant',
          size: 'Huge',
          type: 'giant',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 15,
          hitPoints: 138,
          hitDice: '12d12',
          strength: 15,
          dexterity: 9,
          constitution: 21,
          intelligence: 9,
          wisdom: 10,
          charisma: 12,
          challenge: 8,
          xpReward: 3900,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gargoyle',
          size: 'Medium',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 15,
          hitPoints: 52,
          hitDice: '7d8',
          strength: 15,
          dexterity: 11,
          constitution: 16,
          intelligence: 6,
          wisdom: 11,
          charisma: 7,
          challenge: 2,
          xpReward: 450,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gelatinous Cube',
          size: 'Large',
          type: 'ooze',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 6,
          hitPoints: 84,
          hitDice: '8d10',
          strength: 14,
          dexterity: 3,
          constitution: 20,
          intelligence: 1,
          wisdom: 6,
          charisma: 1,
          challenge: 2,
          xpReward: 450,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ghast',
          size: 'Medium',
          type: 'undead',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 13,
          hitPoints: 36,
          hitDice: '8d8',
          strength: 16,
          dexterity: 17,
          constitution: 10,
          intelligence: 11,
          wisdom: 10,
          charisma: 8,
          challenge: 2,
          xpReward: 450,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ghost',
          size: 'Medium',
          type: 'undead',
          subtype: 'none',
          alignment: 'any alignment',
          armorClass: 11,
          hitPoints: 45,
          hitDice: '10d8',
          strength: 7,
          dexterity: 13,
          constitution: 10,
          intelligence: 10,
          wisdom: 12,
          charisma: 17,
          challenge: 4,
          xpReward: 1100,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Ghoul',
          size: 'Medium',
          type: 'undead',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 12,
          hitPoints: 22,
          hitDice: '5d8',
          strength: 13,
          dexterity: 15,
          constitution: 10,
          intelligence: 7,
          wisdom: 10,
          charisma: 6,
          challenge: 1,
          xpReward: 200,
          weakness: 'holy',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Ape',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 157,
          hitDice: '15d12',
          strength: 23,
          dexterity: 14,
          constitution: 18,
          intelligence: 7,
          wisdom: 12,
          charisma: 7,
          challenge: 7,
          xpReward: 2900,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Badger',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 13,
          hitDice: '2d8',
          strength: 13,
          dexterity: 10,
          constitution: 15,
          intelligence: 2,
          wisdom: 12,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Bat',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 22,
          hitDice: '4d10',
          strength: 15,
          dexterity: 16,
          constitution: 11,
          intelligence: 2,
          wisdom: 12,
          charisma: 6,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Boar',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 42,
          hitDice: '5d10',
          strength: 17,
          dexterity: 10,
          constitution: 16,
          intelligence: 2,
          wisdom: 7,
          charisma: 5,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Centipede',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d6',
          strength: 25,
          dexterity: 9,
          constitution: 23,
          intelligence: 10,
          wisdom: 14,
          charisma: 13,
          challenge: 0.25,
          xpReward: 100,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Constrictor Snake',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 60,
          hitDice: '8d12',
          strength: 19,
          dexterity: 14,
          constitution: 12,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Crab',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 15,
          hitPoints: 13,
          hitDice: '3d8',
          strength: 13,
          dexterity: 15,
          constitution: 11,
          intelligence: 1,
          wisdom: 9,
          charisma: 3,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Crocodile',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 85,
          hitDice: '9d12',
          strength: 21,
          dexterity: 9,
          constitution: 17,
          intelligence: 2,
          wisdom: 10,
          charisma: 7,
          challenge: 5,
          xpReward: 1800,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Eagle',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 26,
          hitDice: '4d10',
          strength: 16,
          dexterity: 17,
          constitution: 13,
          intelligence: 8,
          wisdom: 14,
          charisma: 10,
          challenge: 1,
          xpReward: 200,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Elk',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 15,
          hitPoints: 42,
          hitDice: '5d12',
          strength: 19,
          dexterity: 16,
          constitution: 14,
          intelligence: 7,
          wisdom: 14,
          charisma: 10,
          challenge: 2,
          xpReward: 450,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Fire Beetle',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d6',
          strength: 8,
          dexterity: 10,
          constitution: 12,
          intelligence: 1,
          wisdom: 7,
          charisma: 3,
          challenge: 0,
          xpReward: 10,
          weakness: 'water',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Frog',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 18,
          hitDice: '4d8',
          strength: 12,
          dexterity: 13,
          constitution: 11,
          intelligence: 2,
          wisdom: 10,
          charisma: 3,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Goat',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 19,
          hitDice: '3d10',
          strength: 17,
          dexterity: 11,
          constitution: 12,
          intelligence: 3,
          wisdom: 12,
          charisma: 6,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Hyena',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 45,
          hitDice: '6d10',
          strength: 16,
          dexterity: 14,
          constitution: 14,
          intelligence: 2,
          wisdom: 12,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Lizard',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d6',
          strength: 25,
          dexterity: 9,
          constitution: 23,
          intelligence: 10,
          wisdom: 14,
          charisma: 13,
          challenge: 0.25,
          xpReward: 100,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Octopus',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d6',
          strength: 25,
          dexterity: 9,
          constitution: 23,
          intelligence: 10,
          wisdom: 14,
          charisma: 13,
          challenge: 1,
          xpReward: 200,
          weakness: 'lightning/earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Owl',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d6',
          strength: 25,
          dexterity: 9,
          constitution: 23,
          intelligence: 10,
          wisdom: 14,
          charisma: 13,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Poisonous Snake',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 10,
          dexterity: 18,
          constitution: 13,
          intelligence: 2,
          wisdom: 10,
          charisma: 3,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Rat',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 7,
          hitDice: '1d6',
          strength: 15,
          dexterity: 15,
          constitution: 11,
          intelligence: 2,
          wisdom: 10,
          charisma: 4,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Scorpian',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 15,
          hitPoints: 12,
          hitDice: '2d6',
          strength: 15,
          dexterity: 10,
          constitution: 10,
          intelligence: 5,
          wisdom: 10,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Seahorse',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 16,
          hitDice: '3d10',
          strength: 12,
          dexterity: 15,
          constitution: 11,
          intelligence: 2,
          wisdom: 12,
          charisma: 5,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'earth',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Shark',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 126,
          hitDice: '11d12',
          strength: 25,
          dexterity: 9,
          constitution: 21,
          intelligence: 1,
          wisdom: 10,
          charisma: 5,
          challenge: 5,
          xpReward: 1800,
          weakness: 'earth/lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Spider',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 26,
          hitDice: '4d10',
          strength: 14,
          dexterity: 16,
          constitution: 12,
          intelligence: 2,
          wisdom: 11,
          charisma: 4,
          challenge: 1,
          xpReward: 200,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Vulture',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 10,
          hitPoints: 22,
          hitDice: '3d10',
          strength: 15,
          dexterity: 10,
          constitution: 15,
          intelligence: 6,
          wisdom: 12,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
          weakness: 'lightning',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Giant Wasp',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 13,
          hitDice: '3d8',
          strength: 10,
          dexterity: 14,
          constitution: 10,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 0.5,
          xpReward: 100,
          weakness: 'fire',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gibbering Mouther',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 9,
          hitPoints: 67,
          hitDice: '4d6',
          strength: 10,
          dexterity: 8,
          constitution: 19,
          intelligence: 1,
          wisdom: 10,
          charisma: 4,
          challenge: 1,
          xpReward: 100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Glabrezu',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 9,
          hitPoints: 67,
          hitDice: '4d6',
          strength: 10,
          dexterity: 8,
          constitution: 19,
          intelligence: 1,
          wisdom: 10,
          charisma: 4,
          challenge: 1.5,
          xpReward: 100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Gladiator',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 9,
          hitPoints: 67,
          hitDice: '4d6',
          strength: 10,
          dexterity: 8,
          constitution: 19,
          intelligence: 1,
          wisdom: 10,
          charisma: 4,
          challenge: 1,
          xpReward: 100,
          weakness: 'none',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: 'Guard',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 16,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 13,
          dexterity: 12,
          constitution: 12,
          intelligence: 10,
          wisdom: 11,
          charisma: 10,
          challenge: 0.125,
          xpReward: 25,
          weakness: 'fire/poison',
          createdAt: new Date(),
          updatedAt: new Date(),
        },

      ],
      { returning: true }
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Enemies', null, {});
    await queryInterface.bulkDelete('Quests', null, {});
    return queryInterface.bulkDelete('Users', null, {});
  }
};
