"""create items

Revision ID: 383dbe0983df
Revises: 
Create Date: 2020-07-01 14:12:48.668935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383dbe0983df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('companyId', sa.Integer(), nullable=True),
    sa.Column('imgSrc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
