"""Add validation to items

Revision ID: 2b37c15fb2c6
Revises: 46918f7dc9da
Create Date: 2020-07-01 18:17:56.837669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b37c15fb2c6'
down_revision = '46918f7dc9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'companyId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('items', 'companyId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
