version: '3.3'

services:
  web:
    build: .
    image: bamorgan13/eventlight
    ports:
      - 5000:5000
    # networks:
    #   - eventlight
    # depends_on:
    #   - db
    env_file:
      - .env
  #   environment:
  #     - MONGO_URI=mongodb://mongo_db/nodeapp
  #     - SECRET_OR_KEY=secret
  # db:
  #   image: mongo:4.2
  #   volumes:
  #     - mongo-db:/data/db
  #   networks:
  #     eventlight:
  #       aliases:
  #         - 'mongo_db'

# networks:
#   eventlight:
#     driver: bridge
# volumes:
#   mongo-db:
