# Step 1: Base image for node build - use alpine for node version 14
#         Name it build-stage

# Step 2: Set the working directory to /app

# Step 3: Add package files

# Step 4: Install dependencies using npm
#   To keep the image small, (force) clean the npm cache after
#   Chain the commands to reduce the number of layers in the image

# Step 5: Add application files

# Step 6: Build application

# Step 7: Bring in the base image for NGINX (alpine)

# Step 8: Expose the proper nginx port for http

# Step 9: Set working directory to the html folder for nginx

# Step 10: Copy over the build files from build-stage

# Step 11: Reaplce the default NGINX config with the application's version
