# Python CircleCI 2.0 configuration file
# Updating CircleCI configuration from v1 to v2
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build images
          command: |
            docker build -t jupyterhub/jupyterhub .
            docker build -t jupyterhub/jupyterhub-onbuild onbuild
            docker build -t jupyterhub/jupyterhub:alpine -f dockerfiles/Dockerfile.alpine .
            docker build -t jupyterhub/singleuser singleuser
      - run:
          name: smoke test jupyterhub
          command: |
            docker run --rm -it jupyterhub/jupyterhub jupyterhub --help
      - run:
          name: verify static files
          command: |
            docker run --rm -it -v $PWD/dockerfiles:/io jupyterhub/jupyterhub python3 /io/test.py

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build
