CREATE TABLE edible_seeds
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(300),
  type VARCHAR(255),
  price_per_pound FLOAT,
  in_stock BOOLEAN
);

INSERT INTO edible_seeds
  (name, type, price_per_pound, in_stock)
VALUES
  ('Chia', 'Pseudocereal', 6.95, true),
  ('Flax', 'Pseudocereal', 6.90, true),
  ('Amaranth', 'Pseudocereal', 14.99, true),
  ('Quinoa', 'Pseudocereal', 12.49, false),
  ('Sesame', 'Pseudocereal', 13.49, true),
  ('Hemp', 'Other', 10.99, true),
  ('Chickpea', 'Legume', 7.99, true),
  ('Pea', 'Legume', 7.50, false),
  ('Soybean', 'Legume', 12.99, true),
  ('Acorn', 'Nut', 11.99, true),
  ('Almond', 'Nut', 13.99, true),
  ('Beech', 'Nut', 10.94, true),
  ('Chestnut', 'Nut', 13.99, true),
  ('Water Chestnut', 'Nut', 9.99, false),
  ('Macadamia', 'Nut', 25.00, true),
  ('Pistachio', 'Nut', 20.00, true),
  ('Pine nuts', 'Nut-like gymnosperm', 23.00, true),
  ('Pecan', 'Nut', 6.99, true),
  ('Juniper berries', 'Nut-like gymnosperm', 11.99, true),
  ('Cashew', 'Nut', 23.61, true),
  ('Hazelnut', 'Nut', 25.49, true),
  ('Sunflower seed', 'Other', 9.99, true),
  ('Poppy seed', 'Other', 12.99, true),
  ('Barley', 'Cereal', 9.99, true),
  ('Maize', 'Cereal', 6.98, true),
  ('Oats', 'Cereal', 9.99, true),
  ('Rice', 'Cereal', 7.90, true),
  ('Rye', 'Cereal', 9.87, true),
  ('Spelt', 'Cereal', 7.50, true),
  ('Wheat berries', 'Cereal', 2.50, false),
  ('Buckwheat', 'Pseudocereal', 5.60, true),
  ('Jackfruit', 'Other', 15.00, true),
  ('Durian', 'Other', 8.26, false),
  ('Lotus seed', 'Other', 12.99, true),
  ('Ginko', 'Nut-like gymnosperm', 12.80, true),
  ('Peanut', 'Legume', 5.99, true),
  ('Pumpkin seed', 'Other', 5.99, true),
  ('Watermelon seed', 'Other', 6.99, true),
  ('Pomegranate seed', 'Other', 27.63, true),
  ('Cacao bean', 'Other', 12.99, true);
