'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Traits", [

      // biological sex
      { TraitTypeId: 2, trait: "male" },
      { TraitTypeId: 2, trait: "female" },
      { TraitTypeId: 2, trait: "intersex" },
      { TraitTypeId: 2, trait: "none" },

      // gender
      { TraitTypeId: 3, trait: "boy / man / guy (he/him/his)" }, // 10
      { TraitTypeId: 3, trait: "girl / woman / gal (she/her/hers)" },
      { TraitTypeId: 3, trait: "neutral (they/them/theirs)" },
      { TraitTypeId: 3, trait: "fluid (varies)" },

      // age
      { TraitTypeId: 4, trait: "baby" },
      { TraitTypeId: 4, trait: "child" },
      { TraitTypeId: 4, trait: "teenager" },
      { TraitTypeId: 4, trait: "young adult" },
      { TraitTypeId: 4, trait: "middle-aged adult" },
      { TraitTypeId: 4, trait: "elder" },
      { TraitTypeId: 4, trait: "ancient one" },
      { TraitTypeId: 4, trait: "immortal" },

      // species
      { TraitTypeId: 5, trait: "human" },
      { TraitTypeId: 5, trait: "angel" },
      { TraitTypeId: 5, trait: "demon" },
      { TraitTypeId: 5, trait: "demigod" },
      { TraitTypeId: 5, trait: "deity" },
      { TraitTypeId: 5, trait: "dwarf" },
      { TraitTypeId: 5, trait: "elf" },
      { TraitTypeId: 5, trait: "fairy" },
      { TraitTypeId: 5, trait: "pixie" },
      { TraitTypeId: 5, trait: "sprite" },
      { TraitTypeId: 5, trait: "mermaid" },
      { TraitTypeId: 5, trait: "dryad" },
      { TraitTypeId: 5, trait: "nymph" },
      { TraitTypeId: 5, trait: "sylph" },
      { TraitTypeId: 5, trait: "satyr" },
      { TraitTypeId: 5, trait: "halfling" },
      { TraitTypeId: 5, trait: "dragonborn" },
      { TraitTypeId: 5, trait: "aasimar" },
      { TraitTypeId: 5, trait: "tiefling" },
      { TraitTypeId: 5, trait: "centaur" },
      { TraitTypeId: 5, trait: "harpy" },
      { TraitTypeId: 5, trait: "ghost" },
      { TraitTypeId: 5, trait: "vampire" },
      { TraitTypeId: 5, trait: "werewolf" },
      { TraitTypeId: 5, trait: "dog" },
      { TraitTypeId: 5, trait: "cat" },
      { TraitTypeId: 5, trait: "rat" },
      { TraitTypeId: 5, trait: "robot" },
      { TraitTypeId: 5, trait: "half-human" },

      // region
      { TraitTypeId: 6, trait: "arctic" },
      { TraitTypeId: 6, trait: "north america" },
      { TraitTypeId: 6, trait: "south america" },
      { TraitTypeId: 6, trait: "europe" },
      { TraitTypeId: 6, trait: "asia" },
      { TraitTypeId: 6, trait: "africa" },
      { TraitTypeId: 6, trait: "oceania" },

      { TraitTypeId: 6, trait: "Afghanistan" },
      { TraitTypeId: 6, trait: "Albania" },
      { TraitTypeId: 6, trait: "Algeria" },
      { TraitTypeId: 6, trait: "Andorra" },
      { TraitTypeId: 6, trait: "Angola" },
      { TraitTypeId: 6, trait: "Antigua and Barbuda" },
      { TraitTypeId: 6, trait: "Argentina" },
      { TraitTypeId: 6, trait: "Armenia" },
      { TraitTypeId: 6, trait: "Australia" },
      { TraitTypeId: 6, trait: "Austria" },
      { TraitTypeId: 6, trait: "Azerbaijan" },
      { TraitTypeId: 6, trait: "The Bahamas" },
      { TraitTypeId: 6, trait: "Bahrain" },
      { TraitTypeId: 6, trait: "Bangladesh" },
      { TraitTypeId: 6, trait: "Barbados" },
      { TraitTypeId: 6, trait: "Belarus" },
      { TraitTypeId: 6, trait: "Belgium" },
      { TraitTypeId: 6, trait: "Belize" },
      { TraitTypeId: 6, trait: "Benin" },
      { TraitTypeId: 6, trait: "Bhutan" },
      { TraitTypeId: 6, trait: "Bolivia" },
      { TraitTypeId: 6, trait: "Bosnia and Herzegovina" },
      { TraitTypeId: 6, trait: "Botswana" },
      { TraitTypeId: 6, trait: "Brazil" },
      { TraitTypeId: 6, trait: "Brunei" },
      { TraitTypeId: 6, trait: "Bulgaria" },
      { TraitTypeId: 6, trait: "Burkina Faso" },
      { TraitTypeId: 6, trait: "Burundi" },
      { TraitTypeId: 6, trait: "Cabo Verde" },
      { TraitTypeId: 6, trait: "Cambodia" },
      { TraitTypeId: 6, trait: "Cameroon" },
      { TraitTypeId: 6, trait: "Canada" },
      { TraitTypeId: 6, trait: "Central African Republic" },
      { TraitTypeId: 6, trait: "Chad" },
      { TraitTypeId: 6, trait: "Chile" },
      { TraitTypeId: 6, trait: "China" },
      { TraitTypeId: 6, trait: "Colombia" },
      { TraitTypeId: 6, trait: "Comoros" },
      { TraitTypeId: 6, trait: "Congo, Democratic Republic of the" },
      { TraitTypeId: 6, trait: "Congo, Republic of the" },
      { TraitTypeId: 6, trait: "Costa Rica" },
      { TraitTypeId: 6, trait: "Côte d’Ivoire" },
      { TraitTypeId: 6, trait: "Croatia" },
      { TraitTypeId: 6, trait: "Cuba" },
      { TraitTypeId: 6, trait: "Cyprus" },
      { TraitTypeId: 6, trait: "Czech Republic" },
      { TraitTypeId: 6, trait: "Denmark" },
      { TraitTypeId: 6, trait: "Djibouti" },
      { TraitTypeId: 6, trait: "Dominica" },
      { TraitTypeId: 6, trait: "Dominican Republic" },
      { TraitTypeId: 6, trait: "East Timor (Timor-Leste)" },
      { TraitTypeId: 6, trait: "Ecuador" },
      { TraitTypeId: 6, trait: "Egypt" },
      { TraitTypeId: 6, trait: "El Salvador" },
      { TraitTypeId: 6, trait: "Equatorial Guinea" },
      { TraitTypeId: 6, trait: "Eritrea" },
      { TraitTypeId: 6, trait: "Estonia" },
      { TraitTypeId: 6, trait: "Eswatini" },
      { TraitTypeId: 6, trait: "Ethiopia" },
      { TraitTypeId: 6, trait: "Fiji" },
      { TraitTypeId: 6, trait: "Finland" },
      { TraitTypeId: 6, trait: "France" },
      { TraitTypeId: 6, trait: "Gabon" },
      { TraitTypeId: 6, trait: "The Gambia" },
      { TraitTypeId: 6, trait: "Georgia" },
      { TraitTypeId: 6, trait: "Germany" },
      { TraitTypeId: 6, trait: "Ghana" },
      { TraitTypeId: 6, trait: "Greece" },
      { TraitTypeId: 6, trait: "Grenada" },
      { TraitTypeId: 6, trait: "Guatemala" },
      { TraitTypeId: 6, trait: "Guinea" },
      { TraitTypeId: 6, trait: "Guinea-Bissau" },
      { TraitTypeId: 6, trait: "Guyana" },
      { TraitTypeId: 6, trait: "Haiti" },
      { TraitTypeId: 6, trait: "Honduras" },
      { TraitTypeId: 6, trait: "Hungary" },
      { TraitTypeId: 6, trait: "Iceland" },
      { TraitTypeId: 6, trait: "India" },
      { TraitTypeId: 6, trait: "Indonesia" },
      { TraitTypeId: 6, trait: "Iran" },
      { TraitTypeId: 6, trait: "Iraq" },
      { TraitTypeId: 6, trait: "Ireland" },
      { TraitTypeId: 6, trait: "Israel" },
      { TraitTypeId: 6, trait: "Italy" },
      { TraitTypeId: 6, trait: "Jamaica" },
      { TraitTypeId: 6, trait: "Japan" },
      { TraitTypeId: 6, trait: "Jordan" },
      { TraitTypeId: 6, trait: "Kazakhstan" },
      { TraitTypeId: 6, trait: "Kenya" },
      { TraitTypeId: 6, trait: "Kiribati" },
      { TraitTypeId: 6, trait: "Korea, North" },
      { TraitTypeId: 6, trait: "Korea, South" },
      { TraitTypeId: 6, trait: "Kosovo" },
      { TraitTypeId: 6, trait: "Kuwait" },
      { TraitTypeId: 6, trait: "Kyrgyzstan" },
      { TraitTypeId: 6, trait: "Laos" },
      { TraitTypeId: 6, trait: "Latvia" },
      { TraitTypeId: 6, trait: "Lebanon" },
      { TraitTypeId: 6, trait: "Lesotho" },
      { TraitTypeId: 6, trait: "Liberia" },
      { TraitTypeId: 6, trait: "Libya" },
      { TraitTypeId: 6, trait: "Liechtenstein" },
      { TraitTypeId: 6, trait: "Lithuania" },
      { TraitTypeId: 6, trait: "Luxembourg" },
      { TraitTypeId: 6, trait: "Madagascar" },
      { TraitTypeId: 6, trait: "Malawi" },
      { TraitTypeId: 6, trait: "Malaysia" },
      { TraitTypeId: 6, trait: "Maldives" },
      { TraitTypeId: 6, trait: "Mali" },
      { TraitTypeId: 6, trait: "Malta" },
      { TraitTypeId: 6, trait: "Marshall Islands" },
      { TraitTypeId: 6, trait: "Mauritania" },
      { TraitTypeId: 6, trait: "Mauritius" },
      { TraitTypeId: 6, trait: "Mexico" },
      { TraitTypeId: 6, trait: "Micronesia, Federated States of" },
      { TraitTypeId: 6, trait: "Moldova" },
      { TraitTypeId: 6, trait: "Monaco" },
      { TraitTypeId: 6, trait: "Mongolia" },
      { TraitTypeId: 6, trait: "Montenegro" },
      { TraitTypeId: 6, trait: "Morocco" },
      { TraitTypeId: 6, trait: "Mozambique" },
      { TraitTypeId: 6, trait: "Myanmar (Burma)" },
      { TraitTypeId: 6, trait: "Namibia" },
      { TraitTypeId: 6, trait: "Nauru" },
      { TraitTypeId: 6, trait: "Nepal" },
      { TraitTypeId: 6, trait: "Netherlands" },
      { TraitTypeId: 6, trait: "New Zealand" },
      { TraitTypeId: 6, trait: "Nicaragua" },
      { TraitTypeId: 6, trait: "Niger" },
      { TraitTypeId: 6, trait: "Nigeria" },
      { TraitTypeId: 6, trait: "North Macedonia" },
      { TraitTypeId: 6, trait: "Norway" },
      { TraitTypeId: 6, trait: "Oman" },
      { TraitTypeId: 6, trait: "Pakistan" },
      { TraitTypeId: 6, trait: "Palau" },
      { TraitTypeId: 6, trait: "Panama" },
      { TraitTypeId: 6, trait: "Papua New Guinea" },
      { TraitTypeId: 6, trait: "Paraguay" },
      { TraitTypeId: 6, trait: "Peru" },
      { TraitTypeId: 6, trait: "Philippines" },
      { TraitTypeId: 6, trait: "Poland" },
      { TraitTypeId: 6, trait: "Portugal" },
      { TraitTypeId: 6, trait: "Qatar" },
      { TraitTypeId: 6, trait: "Romania" },
      { TraitTypeId: 6, trait: "Russia" },
      { TraitTypeId: 6, trait: "Rwanda" },
      { TraitTypeId: 6, trait: "Saint Kitts and Nevis" },
      { TraitTypeId: 6, trait: "Saint Lucia" },
      { TraitTypeId: 6, trait: "Saint Vincent and the Grenadines" },
      { TraitTypeId: 6, trait: "Samoa" },
      { TraitTypeId: 6, trait: "San Marino" },
      { TraitTypeId: 6, trait: "Sao Tome and Principe" },
      { TraitTypeId: 6, trait: "Saudi Arabia" },
      { TraitTypeId: 6, trait: "Senegal" },
      { TraitTypeId: 6, trait: "Serbia" },
      { TraitTypeId: 6, trait: "Seychelles" },
      { TraitTypeId: 6, trait: "Sierra Leone" },
      { TraitTypeId: 6, trait: "Singapore" },
      { TraitTypeId: 6, trait: "Slovakia" },
      { TraitTypeId: 6, trait: "Slovenia" },
      { TraitTypeId: 6, trait: "Solomon Islands" },
      { TraitTypeId: 6, trait: "Somalia" },
      { TraitTypeId: 6, trait: "South Africa" },
      { TraitTypeId: 6, trait: "Spain" },
      { TraitTypeId: 6, trait: "Sri Lanka" },
      { TraitTypeId: 6, trait: "Sudan" },
      { TraitTypeId: 6, trait: "Sudan, South" },
      { TraitTypeId: 6, trait: "Suriname" },
      { TraitTypeId: 6, trait: "Sweden" },
      { TraitTypeId: 6, trait: "Switzerland" },
      { TraitTypeId: 6, trait: "Syria" },
      { TraitTypeId: 6, trait: "Taiwan" },
      { TraitTypeId: 6, trait: "Tajikistan" },
      { TraitTypeId: 6, trait: "Tanzania" },
      { TraitTypeId: 6, trait: "Thailand" },
      { TraitTypeId: 6, trait: "Togo" },
      { TraitTypeId: 6, trait: "Tonga" },
      { TraitTypeId: 6, trait: "Trinidad and Tobago" },
      { TraitTypeId: 6, trait: "Tunisia" },
      { TraitTypeId: 6, trait: "Turkey" },
      { TraitTypeId: 6, trait: "Turkmenistan" },
      { TraitTypeId: 6, trait: "Tuvalu" },
      { TraitTypeId: 6, trait: "Uganda" },
      { TraitTypeId: 6, trait: "Ukraine" },
      { TraitTypeId: 6, trait: "United Arab Emirates" },
      { TraitTypeId: 6, trait: "United Kingdom" },
      { TraitTypeId: 6, trait: "United States" },
      { TraitTypeId: 6, trait: "Uruguay" },
      { TraitTypeId: 6, trait: "Uzbekistan" },
      { TraitTypeId: 6, trait: "Vanuatu" },
      { TraitTypeId: 6, trait: "Vatican City" },
      { TraitTypeId: 6, trait: "Venezuela" },
      { TraitTypeId: 6, trait: "Vietnam" },
      { TraitTypeId: 6, trait: "Yemen" },
      { TraitTypeId: 6, trait: "Zambia" },
      { TraitTypeId: 6, trait: "Zimbabwe" },

      // occupation
      // { TraitTypeId: 7, trait: "adventurer" },
      // { TraitTypeId: 7, trait: "noble" },
      // { TraitTypeId: 7, trait: "royalty" },
      // { TraitTypeId: 7, trait: "king" },
      // { TraitTypeId: 7, trait: "queen" },
      // { TraitTypeId: 7, trait: "prince" },
      // { TraitTypeId: 7, trait: "princess" },
      // { TraitTypeId: 7, trait: "sultan" },

      { TraitTypeId: 7, trait: "military" },
      { TraitTypeId: 7, trait: "religion" },
      { TraitTypeId: 7, trait: "government" },
      { TraitTypeId: 7, trait: "law" },
      { TraitTypeId: 7, trait: "crime" },
      { TraitTypeId: 7, trait: "outcast" },
      { TraitTypeId: 7, trait: "hermit" },
      { TraitTypeId: 7, trait: "nobility" },
      { TraitTypeId: 7, trait: "labor" },
      { TraitTypeId: 7, trait: "trade" },
      { TraitTypeId: 7, trait: "craft" },
      { TraitTypeId: 7, trait: "travel" },
      { TraitTypeId: 7, trait: "arts" },
      { TraitTypeId: 7, trait: "academia" },
      { TraitTypeId: 7, trait: "arcane" },
      { TraitTypeId: 7, trait: "adventure" },

      { TraitTypeId: 7, trait: "Artificer" },
      { TraitTypeId: 7, trait: "Barbarian" },
      { TraitTypeId: 7, trait: "Bard" },
      { TraitTypeId: 7, trait: "Cleric" },
      { TraitTypeId: 7, trait: "Druid" },
      { TraitTypeId: 7, trait: "Fighter" },
      { TraitTypeId: 7, trait: "Monk" },
      { TraitTypeId: 7, trait: "Paladin" },
      { TraitTypeId: 7, trait: "Ranger" },
      { TraitTypeId: 7, trait: "Rogue" },
      { TraitTypeId: 7, trait: "Sorcerer" },
      { TraitTypeId: 7, trait: "Warlock" },
      { TraitTypeId: 7, trait: "Wizard" },


      // hair color
      { TraitTypeId: 8, trait: "brown" },
      { TraitTypeId: 8, trait: "red" },
      { TraitTypeId: 8, trait: "orange" },
      { TraitTypeId: 8, trait: "yellow" },
      { TraitTypeId: 8, trait: "green" },
      { TraitTypeId: 8, trait: "blue" },
      { TraitTypeId: 8, trait: "purple" },
      { TraitTypeId: 8, trait: "pink" },
      { TraitTypeId: 8, trait: "white" },
      { TraitTypeId: 8, trait: "gray" },
      { TraitTypeId: 8, trait: "black" },
      { TraitTypeId: 8, trait: "changes" },
      { TraitTypeId: 8, trait: "multi-colored" },

      { TraitTypeId: 8, trait: "pale blonde" },
      { TraitTypeId: 8, trait: "dark blonde" },
      { TraitTypeId: 8, trait: "platinum blonde" },
      { TraitTypeId: 8, trait: "strawberry blonde" },
      { TraitTypeId: 8, trait: "honey blonde" },
      { TraitTypeId: 8, trait: "golden blonde" },
      { TraitTypeId: 8, trait: "flaxen" },
      { TraitTypeId: 8, trait: "bleach blonde" },
      { TraitTypeId: 8, trait: "chestnut brown" },
      { TraitTypeId: 8, trait: "ash brown" },
      { TraitTypeId: 8, trait: "auburn" },
      { TraitTypeId: 8, trait: "copper" },
      { TraitTypeId: 8, trait: "ginger" },
      { TraitTypeId: 8, trait: "golden brown" },
      { TraitTypeId: 8, trait: "light brown" },
      { TraitTypeId: 8, trait: "dark brown" },
      { TraitTypeId: 8, trait: "salt and pepper" },

      // { TraitTypeId: 5, trait: "dyed" },
      // { TraitTypeId: 5, trait: "bleached" },
      // { TraitTypeId: 5, trait: "duo-tone" },
      // { TraitTypeId: 5, trait: "lowlights" },
      // { TraitTypeId: 5, trait: "highlights" },
      // { TraitTypeId: 5, trait: "wig" },

      // hair texture
      { TraitTypeId: 9, trait: "straight" },
      { TraitTypeId: 9, trait: "wavy" },
      { TraitTypeId: 9, trait: "curly" },
      { TraitTypeId: 9, trait: "frizzy" },
      { TraitTypeId: 9, trait: "kinky" },
      { TraitTypeId: 9, trait: "bouncy" },
      { TraitTypeId: 9, trait: "flat" },
      { TraitTypeId: 9, trait: "loose curls" },
      { TraitTypeId: 9, trait: "tight curls" },
      { TraitTypeId: 9, trait: "glossy" },
      { TraitTypeId: 9, trait: "dull" },
      { TraitTypeId: 9, trait: "dry" },
      { TraitTypeId: 9, trait: "greasy" },
      { TraitTypeId: 9, trait: "thin" },
      { TraitTypeId: 9, trait: "thick" },

      // hair length
      { TraitTypeId: 10, trait: "bald" },
      { TraitTypeId: 10, trait: "cropped" },
      { TraitTypeId: 10, trait: "short" },
      { TraitTypeId: 10, trait: "chin-length" },
      { TraitTypeId: 10, trait: "shoulder-length" },
      { TraitTypeId: 10, trait: "long" },
      { TraitTypeId: 10, trait: "waist-length" },
      { TraitTypeId: 10, trait: "floor-length" },

      // hair style
      { TraitTypeId: 9, trait: "loose" },
      { TraitTypeId: 9, trait: "high ponytail" },
      { TraitTypeId: 9, trait: "low ponytail" },
      { TraitTypeId: 9, trait: "ponytail" },
      { TraitTypeId: 9, trait: "loose ponytail" },
      { TraitTypeId: 9, trait: "tight ponytail" },
      { TraitTypeId: 9, trait: "messy ponytail" },
      { TraitTypeId: 9, trait: "braided ponytail" },
      { TraitTypeId: 9, trait: "twintails" },
      { TraitTypeId: 9, trait: "braided twintails" },
      { TraitTypeId: 9, trait: "looped twintails" },
      { TraitTypeId: 9, trait: "bangs" },
      { TraitTypeId: 9, trait: "thin braids" },
      { TraitTypeId: 9, trait: "afro" },
      { TraitTypeId: 9, trait: "braided" },
      { TraitTypeId: 9, trait: "side tail" },
      { TraitTypeId: 9, trait: "dreadlocks" },
      { TraitTypeId: 9, trait: "pompadour" },
      { TraitTypeId: 9, trait: "beehive" },
      { TraitTypeId: 9, trait: "bun" },
      { TraitTypeId: 9, trait: "buns" },
      { TraitTypeId: 9, trait: "mohawk" },
      { TraitTypeId: 9, trait: "pageboy" },
      { TraitTypeId: 9, trait: "pixie" },
      { TraitTypeId: 9, trait: "crewcut" },
      { TraitTypeId: 9, trait: "horsetail" },
      { TraitTypeId: 9, trait: "bouffant" },
      { TraitTypeId: 9, trait: "elaborate hairstyle" },
      { TraitTypeId: 9, trait: "traditional" },
      { TraitTypeId: 9, trait: "goatee" },
      { TraitTypeId: 9, trait: "beard" },
      { TraitTypeId: 9, trait: "sideburns" },
      { TraitTypeId: 9, trait: "cornrows" },
      { TraitTypeId: 9, trait: "layered" },
      { TraitTypeId: 9, trait: "asymmetrical" },
      { TraitTypeId: 9, trait: "bowl cut" },
      { TraitTypeId: 9, trait: "undercut" },
      { TraitTypeId: 9, trait: "buzz cut" },
      { TraitTypeId: 9, trait: "top knot" },
      { TraitTypeId: 9, trait: "ducktail" },
      { TraitTypeId: 9, trait: "fade" },
      { TraitTypeId: 9, trait: "mullet" },
      { TraitTypeId: 9, trait: "quiff" },
      { TraitTypeId: 9, trait: "comb-over" },
      { TraitTypeId: 9, trait: "slicked back" },
      { TraitTypeId: 9, trait: "side part" },
      { TraitTypeId: 9, trait: "spikey" },
      { TraitTypeId: 9, trait: "chignon" },
      { TraitTypeId: 9, trait: "crown braid" },
      { TraitTypeId: 9, trait: "fallera" },
      { TraitTypeId: 9, trait: "feathered" },
      { TraitTypeId: 9, trait: "mop-top" },
      { TraitTypeId: 9, trait: "fontage" },
      { TraitTypeId: 9, trait: "french braid" },
      { TraitTypeId: 9, trait: "french twist" },
      { TraitTypeId: 9, trait: "hime cut" },
      { TraitTypeId: 9, trait: "rattail" },
      { TraitTypeId: 9, trait: "ringlets" },
      { TraitTypeId: 9, trait: "updo" },
      { TraitTypeId: 9, trait: "finger waves" },

      // eye color
      { TraitTypeId: 10, trait: "brown" },
      { TraitTypeId: 10, trait: "red" },
      { TraitTypeId: 10, trait: "orange" },
      { TraitTypeId: 10, trait: "yellow" },
      { TraitTypeId: 10, trait: "green" },
      { TraitTypeId: 10, trait: "blue" },
      { TraitTypeId: 10, trait: "purple" },
      { TraitTypeId: 10, trait: "pink" },
      { TraitTypeId: 10, trait: "white" },
      { TraitTypeId: 10, trait: "gray" },
      { TraitTypeId: 10, trait: "black" },
      { TraitTypeId: 10, trait: "changes" },
      { TraitTypeId: 10, trait: "dichromatic" },
      { TraitTypeId: 10, trait: "heterochromatic" },
      { TraitTypeId: 10, trait: "multi-colored" },

      // skin color
      { TraitTypeId: 11, trait: "pale" },
      { TraitTypeId: 11, trait: "dark" },
      { TraitTypeId: 11, trait: "brown" },
      { TraitTypeId: 11, trait: "red" },
      { TraitTypeId: 11, trait: "orange" },
      { TraitTypeId: 11, trait: "yellow" },
      { TraitTypeId: 11, trait: "green" },
      { TraitTypeId: 11, trait: "blue" },
      { TraitTypeId: 11, trait: "purple" },
      { TraitTypeId: 11, trait: "pink" },
      { TraitTypeId: 11, trait: "white" },
      { TraitTypeId: 11, trait: "gray" },
      { TraitTypeId: 11, trait: "black" },
      { TraitTypeId: 11, trait: "vitiligo" },
      { TraitTypeId: 11, trait: "changes" },
      { TraitTypeId: 11, trait: "multi-colored" },

      { TraitTypeId: 11, trait: "alabaster" },
      { TraitTypeId: 11, trait: "amber" },
      { TraitTypeId: 11, trait: "bay" },
      { TraitTypeId: 11, trait: "bronze" },
      { TraitTypeId: 11, trait: "burnt sienna" },
      { TraitTypeId: 11, trait: "butterscotch" },
      { TraitTypeId: 11, trait: "chestnut" },
      { TraitTypeId: 11, trait: "chocolate" },
      { TraitTypeId: 11, trait: "cinnamon" },
      { TraitTypeId: 11, trait: "coffee" },
      { TraitTypeId: 11, trait: "cocoa" },
      { TraitTypeId: 11, trait: "copper" },
      { TraitTypeId: 11, trait: "cream" },
      { TraitTypeId: 11, trait: "currant" },
      { TraitTypeId: 11, trait: "ebony" },
      { TraitTypeId: 11, trait: "ecru" },
      { TraitTypeId: 11, trait: "fawn" },
      { TraitTypeId: 11, trait: "hazelnut" },
      { TraitTypeId: 11, trait: "henna" },
      { TraitTypeId: 11, trait: "honey" },
      { TraitTypeId: 11, trait: "ivory" },
      { TraitTypeId: 11, trait: "mahogany" },
      { TraitTypeId: 11, trait: "milk" },
      { TraitTypeId: 11, trait: "olive" },
      { TraitTypeId: 11, trait: "peach" },
      { TraitTypeId: 11, trait: "porcelain" },
      { TraitTypeId: 11, trait: "rose" },
      { TraitTypeId: 11, trait: "ruddy" },
      { TraitTypeId: 11, trait: "russet" },
      { TraitTypeId: 11, trait: "sable" },
      { TraitTypeId: 11, trait: "sepia" },
      { TraitTypeId: 11, trait: "taupe" },
      { TraitTypeId: 11, trait: "tawny" },
      { TraitTypeId: 11, trait: "terra-cotta" },
      { TraitTypeId: 11, trait: "toffee" },
      { TraitTypeId: 11, trait: "umber" },
      { TraitTypeId: 11, trait: "honey" },
      { TraitTypeId: 11, trait: "caramel" },
      { TraitTypeId: 11, trait: "tan" },
      { TraitTypeId: 11, trait: "walnut" },
      { TraitTypeId: 11, trait: "sand" },
      { TraitTypeId: 11, trait: "almond" },
      { TraitTypeId: 11, trait: "ashy" },
      { TraitTypeId: 11, trait: "beige" },
      { TraitTypeId: 11, trait: "ochre" },
      { TraitTypeId: 11, trait: "light brown" },
      { TraitTypeId: 11, trait: "dark brown" },

      // physique
      { TraitTypeId: 12, trait: "bony" }, // 30
      { TraitTypeId: 12, trait: "muscular" },
      { TraitTypeId: 12, trait: "short" },
      { TraitTypeId: 12, trait: "tall" },
      { TraitTypeId: 12, trait: "slim" },
      { TraitTypeId: 12, trait: "delicate" },
      { TraitTypeId: 12, trait: "frail" },
      { TraitTypeId: 12, trait: "plump" },
      { TraitTypeId: 12, trait: "thick" },
      { TraitTypeId: 12, trait: "brawny" },
      { TraitTypeId: 12, trait: "athletic" },
      { TraitTypeId: 12, trait: "big-bellied" },
      { TraitTypeId: 12, trait: "dwarfen" },
      { TraitTypeId: 12, trait: "broad" },
      { TraitTypeId: 12, trait: "busty" },
      { TraitTypeId: 12, trait: "buxom" },
      { TraitTypeId: 12, trait: "chubby" },
      { TraitTypeId: 12, trait: "colossal" },
      { TraitTypeId: 12, trait: "compact" },
      { TraitTypeId: 12, trait: "curvy" },
      { TraitTypeId: 12, trait: "dainty" },
      { TraitTypeId: 12, trait: "fit" },
      { TraitTypeId: 12, trait: "firm" },
      { TraitTypeId: 12, trait: "flabby" },
      { TraitTypeId: 12, trait: "fleshy" },
      { TraitTypeId: 12, trait: "flexible" },
      { TraitTypeId: 12, trait: "gangly" },
      { TraitTypeId: 12, trait: "graceful" },
      { TraitTypeId: 12, trait: "heavy" },
      { TraitTypeId: 12, trait: "awkward" },
      { TraitTypeId: 12, trait: "hulking" },
      { TraitTypeId: 12, trait: "hunched" },
      { TraitTypeId: 12, trait: "herculean" },
      { TraitTypeId: 12, trait: "humpbacked" },
      { TraitTypeId: 12, trait: "husky" },
      { TraitTypeId: 12, trait: "lanky" },
      { TraitTypeId: 12, trait: "large" },
      { TraitTypeId: 12, trait: "lean" },
      { TraitTypeId: 12, trait: "leggy" },
      { TraitTypeId: 12, trait: "limber" },
      { TraitTypeId: 12, trait: "limp" },
      { TraitTypeId: 12, trait: "lithe" },
      { TraitTypeId: 12, trait: "long-limbed" },
      { TraitTypeId: 12, trait: "narrow" },
      { TraitTypeId: 12, trait: "nimble" },
      { TraitTypeId: 12, trait: "petite" },
      { TraitTypeId: 12, trait: "paunchy" },
      { TraitTypeId: 12, trait: "fat" },
      { TraitTypeId: 12, trait: "portly" },
      { TraitTypeId: 12, trait: "pudgy" },
      { TraitTypeId: 12, trait: "runty" },
      { TraitTypeId: 12, trait: "scrawny" },
      { TraitTypeId: 12, trait: "shrimpy" },
      { TraitTypeId: 12, trait: "shriveled" },
      { TraitTypeId: 12, trait: "sinewy" },
      { TraitTypeId: 12, trait: "skeletal" },
      { TraitTypeId: 12, trait: "slender" },
      { TraitTypeId: 12, trait: "slouched" },
      { TraitTypeId: 12, trait: "slim" },
      { TraitTypeId: 12, trait: "soft" },
      { TraitTypeId: 12, trait: "spry" },
      { TraitTypeId: 12, trait: "squat" },
      { TraitTypeId: 12, trait: "stiff" },
      { TraitTypeId: 12, trait: "stocky" },
      { TraitTypeId: 12, trait: "stout" },
      { TraitTypeId: 12, trait: "strapping" },
      { TraitTypeId: 12, trait: "supple" },
      { TraitTypeId: 12, trait: "thick" },
      { TraitTypeId: 12, trait: "towering" },
      { TraitTypeId: 12, trait: "trim" },
      { TraitTypeId: 12, trait: "voluptuous" },
      { TraitTypeId: 12, trait: "willowy" },
      { TraitTypeId: 12, trait: "wiry" },
      { TraitTypeId: 12, trait: "withered" },
      { TraitTypeId: 12, trait: "wobbly" },
      { TraitTypeId: 12, trait: "toned" },
      { TraitTypeId: 12, trait: "knobby" },
      { TraitTypeId: 12, trait: "well-built" },
      { TraitTypeId: 12, trait: "average" },
      { TraitTypeId: 12, trait: "toned" },

      // personality
      { TraitTypeId: 14, trait: "extroverted" },
      { TraitTypeId: 14, trait: "introverted" },
      { TraitTypeId: 14, trait: "cautious" },
      { TraitTypeId: 14, trait: "adventurous" },
      { TraitTypeId: 14, trait: "conscientous" },
      { TraitTypeId: 14, trait: "easy-going" },
      { TraitTypeId: 14, trait: "empathetic" },
      { TraitTypeId: 14, trait: "selfish" },
      { TraitTypeId: 14, trait: "moody" },
      { TraitTypeId: 14, trait: "calm" },

      { TraitTypeId: 14, trait: "intuitive" },
      { TraitTypeId: 14, trait: "thinking" },
      { TraitTypeId: 14, trait: "feeling" },
      { TraitTypeId: 14, trait: "observant" },
      { TraitTypeId: 14, trait: "judging" },
      { TraitTypeId: 14, trait: "prospecting" },
      { TraitTypeId: 14, trait: "Architect (INTJ)" },
      { TraitTypeId: 14, trait: "Logician (INTP)" },
      { TraitTypeId: 14, trait: "Commander (ENTJ)" },
      { TraitTypeId: 14, trait: "Debater (ENTP)" },
      { TraitTypeId: 14, trait: "Advocate (INFJ)" },
      { TraitTypeId: 14, trait: "Mediator (INFP)" },
      { TraitTypeId: 14, trait: "Protagonist (ENFJ)" },
      { TraitTypeId: 14, trait: "Campaigner (ENFP)" },
      { TraitTypeId: 14, trait: "Logistician (ISTJ)" },
      { TraitTypeId: 14, trait: "Defender (ISFJ)" },
      { TraitTypeId: 14, trait: "Executive (ESTJ)" },
      { TraitTypeId: 14, trait: "Consule (ESFJ)" },
      { TraitTypeId: 14, trait: "Virtuoso (ISTP)" },
      { TraitTypeId: 14, trait: "Adventurer (ISFP)" },
      { TraitTypeId: 14, trait: "Entrepreneur (ESTP)" },
      { TraitTypeId: 14, trait: "Entertainer (ESFP)" },
      { TraitTypeId: 14, trait: "analytical" },
      { TraitTypeId: 14, trait: "diplomatic" },
      { TraitTypeId: 14, trait: "curious" },
      { TraitTypeId: 14, trait: "practical" },

      { TraitTypeId: 14, trait: "adaptable" },
      { TraitTypeId: 14, trait: "affable" },
      { TraitTypeId: 14, trait: "affectionate" },
      { TraitTypeId: 14, trait: "agreeable" },
      { TraitTypeId: 14, trait: "ambitious" },
      { TraitTypeId: 14, trait: "amiable" },
      { TraitTypeId: 14, trait: "amicable" },
      { TraitTypeId: 14, trait: "amusing" },
      { TraitTypeId: 14, trait: "brave" },
      { TraitTypeId: 14, trait: "bright" },
      { TraitTypeId: 14, trait: "broad-minded" },
      { TraitTypeId: 14, trait: "careful" },
      { TraitTypeId: 14, trait: "charming" },
      { TraitTypeId: 14, trait: "communicative" },
      { TraitTypeId: 14, trait: "compassionate" },
      { TraitTypeId: 14, trait: "conscientious" },
      { TraitTypeId: 14, trait: "considerate" },
      { TraitTypeId: 14, trait: "convivial" },
      { TraitTypeId: 14, trait: "courageous" },
      { TraitTypeId: 14, trait: "courteous" },
      { TraitTypeId: 14, trait: "creative" },
      { TraitTypeId: 14, trait: "decisive" },
      { TraitTypeId: 14, trait: "determined" },
      { TraitTypeId: 14, trait: "diligent" },
      { TraitTypeId: 14, trait: "diplomatic" },
      { TraitTypeId: 14, trait: "discreet" },
      { TraitTypeId: 14, trait: "dynamic" },
      { TraitTypeId: 14, trait: "easygoing" },
      { TraitTypeId: 14, trait: "emotional" },
      { TraitTypeId: 14, trait: "energetic" },
      { TraitTypeId: 14, trait: "enthusiastic" },
      { TraitTypeId: 14, trait: "exuberant" },
      { TraitTypeId: 14, trait: "fair-minded" },
      { TraitTypeId: 14, trait: "faithful" },
      { TraitTypeId: 14, trait: "fearless" },
      { TraitTypeId: 14, trait: "forceful" },
      { TraitTypeId: 14, trait: "frank" },
      { TraitTypeId: 14, trait: "friendly" },
      { TraitTypeId: 14, trait: "funny" },
      { TraitTypeId: 14, trait: "generous" },
      { TraitTypeId: 14, trait: "gentle" },
      { TraitTypeId: 14, trait: "good" },
      { TraitTypeId: 14, trait: "gregarious" },
      { TraitTypeId: 14, trait: "hard-working" },
      { TraitTypeId: 14, trait: "helpful" },
      { TraitTypeId: 14, trait: "honest" },
      { TraitTypeId: 14, trait: "humorous" },
      { TraitTypeId: 14, trait: "imaginative" },
      { TraitTypeId: 14, trait: "impartial" },
      { TraitTypeId: 14, trait: "independent" },
      { TraitTypeId: 14, trait: "intellectual" },
      { TraitTypeId: 14, trait: "intelligent" },
      { TraitTypeId: 14, trait: "intuitive" },
      { TraitTypeId: 14, trait: "inventive" },
      { TraitTypeId: 14, trait: "kind" },
      { TraitTypeId: 14, trait: "loving" },
      { TraitTypeId: 14, trait: "loyal" },
      { TraitTypeId: 14, trait: "modest" },
      { TraitTypeId: 14, trait: "neat" },
      { TraitTypeId: 14, trait: "nice" },
      { TraitTypeId: 14, trait: "optimistic" },
      { TraitTypeId: 14, trait: "passionate" },
      { TraitTypeId: 14, trait: "patient" },
      { TraitTypeId: 14, trait: "persistent" },
      { TraitTypeId: 14, trait: "pioneering" },
      { TraitTypeId: 14, trait: "philosophical" },
      { TraitTypeId: 14, trait: "placid" },
      { TraitTypeId: 14, trait: "plucky" },
      { TraitTypeId: 14, trait: "polite" },
      { TraitTypeId: 14, trait: "powerful" },
      { TraitTypeId: 14, trait: "practical" },
      { TraitTypeId: 14, trait: "pro-active" },
      { TraitTypeId: 14, trait: "quick-witted" },
      { TraitTypeId: 14, trait: "quiet" },
      { TraitTypeId: 14, trait: "rational" },
      { TraitTypeId: 14, trait: "reliable" },
      { TraitTypeId: 14, trait: "reserved" },
      { TraitTypeId: 14, trait: "resourceful" },
      { TraitTypeId: 14, trait: "romantic" },
      { TraitTypeId: 14, trait: "self-confident" },
      { TraitTypeId: 14, trait: "self-disciplined" },
      { TraitTypeId: 14, trait: "sensible" },
      { TraitTypeId: 14, trait: "sensitive" },
      { TraitTypeId: 14, trait: "shy" },
      { TraitTypeId: 14, trait: "sincere" },
      { TraitTypeId: 14, trait: "sociable" },
      { TraitTypeId: 14, trait: "straightforward" },
      { TraitTypeId: 14, trait: "sympathetic" },
      { TraitTypeId: 14, trait: "thoughtful" },
      { TraitTypeId: 14, trait: "tidy" },
      { TraitTypeId: 14, trait: "tough" },
      { TraitTypeId: 14, trait: "unassuming" },
      { TraitTypeId: 14, trait: "understanding" },
      { TraitTypeId: 14, trait: "versatile" },
      { TraitTypeId: 14, trait: "warmhearted" },
      { TraitTypeId: 14, trait: "willing" },
      { TraitTypeId: 14, trait: "witty" },

      { TraitTypeId: 14, trait: "aggressive" },
      { TraitTypeId: 14, trait: "aloof" },
      { TraitTypeId: 14, trait: "arrogant" },
      { TraitTypeId: 14, trait: "belligerent" },
      { TraitTypeId: 14, trait: "big-headed" },
      { TraitTypeId: 14, trait: "bitchy" },
      { TraitTypeId: 14, trait: "boastful" },
      { TraitTypeId: 14, trait: "bone-idle" },
      { TraitTypeId: 14, trait: "boring" },
      { TraitTypeId: 14, trait: "bossy" },
      { TraitTypeId: 14, trait: "callous" },
      { TraitTypeId: 14, trait: "cantankerous" },
      { TraitTypeId: 14, trait: "careless" },
      { TraitTypeId: 14, trait: "changeable" },
      { TraitTypeId: 14, trait: "clinging" },
      { TraitTypeId: 14, trait: "compulsive" },
      { TraitTypeId: 14, trait: "cowardly" },
      { TraitTypeId: 14, trait: "cruel" },
      { TraitTypeId: 14, trait: "cunning" },
      { TraitTypeId: 14, trait: "cynical" },
      { TraitTypeId: 14, trait: "deceitful" },
      { TraitTypeId: 14, trait: "detached" },
      { TraitTypeId: 14, trait: "dishonest" },
      { TraitTypeId: 14, trait: "dogmatic" },
      { TraitTypeId: 14, trait: "domineering" },
      { TraitTypeId: 14, trait: "finicky" },
      { TraitTypeId: 14, trait: "flirtatious" },
      { TraitTypeId: 14, trait: "foolish" },
      { TraitTypeId: 14, trait: "foolhardy" },
      { TraitTypeId: 14, trait: "fussy" },
      { TraitTypeId: 14, trait: "greedy" },
      { TraitTypeId: 14, trait: "grumpy" },
      { TraitTypeId: 14, trait: "gullible" },
      { TraitTypeId: 14, trait: "harsh" },
      { TraitTypeId: 14, trait: "impatient" },
      { TraitTypeId: 14, trait: "impolite" },
      { TraitTypeId: 14, trait: "impulsive" },
      { TraitTypeId: 14, trait: "inconsiderate" },
      { TraitTypeId: 14, trait: "inconsistent" },
      { TraitTypeId: 14, trait: "indecisive" },
      { TraitTypeId: 14, trait: "indiscreet" },
      { TraitTypeId: 14, trait: "inflexible" },
      { TraitTypeId: 14, trait: "interfering" },
      { TraitTypeId: 14, trait: "intolerant" },
      { TraitTypeId: 14, trait: "irresponsible" },
      { TraitTypeId: 14, trait: "jealous" },
      { TraitTypeId: 14, trait: "lazy" },
      { TraitTypeId: 14, trait: "Machiavellian" },
      { TraitTypeId: 14, trait: "materialistic" },
      { TraitTypeId: 14, trait: "mean" },
      { TraitTypeId: 14, trait: "miserly" },
      { TraitTypeId: 14, trait: "moody" },
      { TraitTypeId: 14, trait: "narrow-minded" },
      { TraitTypeId: 14, trait: "nasty" },
      { TraitTypeId: 14, trait: "naughty" },
      { TraitTypeId: 14, trait: "nervous" },
      { TraitTypeId: 14, trait: "obsessive" },
      { TraitTypeId: 14, trait: "obstinate" },
      { TraitTypeId: 14, trait: "overcritical" },
      { TraitTypeId: 14, trait: "overemotional" },
      { TraitTypeId: 14, trait: "parsimonious" },
      { TraitTypeId: 14, trait: "patronizing" },
      { TraitTypeId: 14, trait: "perverse" },
      { TraitTypeId: 14, trait: "pessimistic" },
      { TraitTypeId: 14, trait: "pompous" },
      { TraitTypeId: 14, trait: "possessive" },
      { TraitTypeId: 14, trait: "pusillanimous" },
      { TraitTypeId: 14, trait: "quarrelsome" },
      { TraitTypeId: 14, trait: "quick-tempered" },
      { TraitTypeId: 14, trait: "resentful" },
      { TraitTypeId: 14, trait: "rude" },
      { TraitTypeId: 14, trait: "ruthless" },
      { TraitTypeId: 14, trait: "sarcastic" },
      { TraitTypeId: 14, trait: "secretive" },
      { TraitTypeId: 14, trait: "selfish" },
      { TraitTypeId: 14, trait: "self-centred" },
      { TraitTypeId: 14, trait: "self-indulgent" },
      { TraitTypeId: 14, trait: "silly" },
      { TraitTypeId: 14, trait: "sneaky" },
      { TraitTypeId: 14, trait: "stingy" },
      { TraitTypeId: 14, trait: "stubborn" },
      { TraitTypeId: 14, trait: "stupid" },
      { TraitTypeId: 14, trait: "superficial" },
      { TraitTypeId: 14, trait: "tactless" },
      { TraitTypeId: 14, trait: "timid" },
      { TraitTypeId: 14, trait: "touchy" },
      { TraitTypeId: 14, trait: "thoughtless" },
      { TraitTypeId: 14, trait: "truculent" },
      { TraitTypeId: 14, trait: "unkind" },
      { TraitTypeId: 14, trait: "unpredictable" },
      { TraitTypeId: 14, trait: "unreliable" },
      { TraitTypeId: 14, trait: "untidy" },
      { TraitTypeId: 14, trait: "untrustworthy" },
      { TraitTypeId: 14, trait: "vague" },
      { TraitTypeId: 14, trait: "vain" },
      { TraitTypeId: 14, trait: "vengeful" },
      { TraitTypeId: 14, trait: "vulgar" },
      { TraitTypeId: 14, trait: "weak-willed" },

      // { TraitTypeId: 9, trait: "cassock" },
      // { TraitTypeId: 9, trait: "robe" },
      // { TraitTypeId: 9, trait: "vestments" },
      // { TraitTypeId: 9, trait: "modest dress" },
      // { TraitTypeId: 9, trait: "cleric robe" },
      // { TraitTypeId: 9, trait: "armor" },
      // { TraitTypeId: 9, trait: "uniform" },
      // { TraitTypeId: 9, trait: "plain shirt and pants" },
      // { TraitTypeId: 9, trait: "dirty clothes" },
      // { TraitTypeId: 9, trait: "" },


      // mannerism
      // { TraitTypeId: 10, trait: "bites nails" },
      // { TraitTypeId: 10, trait: "walks slowly" },
      // { TraitTypeId: 10, trait: "slight stutter" },


      { TraitTypeId: 11, trait: "painting" },
      { TraitTypeId: 11, trait: "coding" }, // 40
      { TraitTypeId: 11, trait: "slaying foes" },
      { TraitTypeId: 12, trait: "riches" },
      { TraitTypeId: 12, trait: "love" },

      { TraitTypeId: 13, trait: "death" },
      { TraitTypeId: 13, trait: "humiliation" }, // 45
      { TraitTypeId: 13, trait: "sickness" },
      { TraitTypeId: 13, trait: "darkness" },
      { TraitTypeId: 13, trait: "commitment" },

      { TraitTypeId: 14, trait: "remembers their past life" },
      { TraitTypeId: 14, trait: "killed an innocent person" }, // 50
      { TraitTypeId: 14, trait: "hid treasure in the mountains" },
      { TraitTypeId: 14, trait: "having an affair with a noble lady" },

      { TraitTypeId: 15, trait: "Sophia" },
      { TraitTypeId: 15, trait: "Ashen" },
      { TraitTypeId: 15, trait: "Dawn" }, // 55
      { TraitTypeId: 15, trait: "Catherine" },
      { TraitTypeId: 15, trait: "Arthur" },
      { TraitTypeId: 15, trait: "Bentley Bingsoo Kim" },
      { TraitTypeId: 15, trait: "Priestess Viridian" },
      { TraitTypeId: 15, trait: "Bora" }, // 60
      { TraitTypeId: 15, trait: "Sung" },
      { TraitTypeId: 15, trait: "Sangsook" },

    ])
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Traits', null, {})
  }
}