language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  
script:
  - node app.js

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js