steps:
  - label: windows-test
    commands:
      - "yarn install --frozen-lockfile --non-interactive --network-timeout 100000"
      - "yarn bazel test //tools/ts-api-guardian:all --noshow_progress"
    plugins:
      - docker#v2.1.0:
          image: "filipesilva/node-bazel-windows:0.0.2"
    agents:
      windows: true
